export const result = {
  meta: {
    beaconId: 'au.csiro-serverless.beacon',
    apiVersion: 'v2.0.0',
    returnedGranularity: 'record',
    receivedRequestSummary: {
      apiVersion: 'v2.0',
      requestedSchemas: [],
      filters: [],
      req_params: {},
      includeResultsetResponses: 'HIT',
      pagination: {
        skip: 0,
        limit: 100,
      },
      requestedGranularity: 'record',
      testMode: false,
    },
    returnedSchemas: [
      {
        entityType: 'biosample',
        schema: 'beacon-dataset-v2.0.0',
      },
    ],
  },
  responseSummary: {
    exists: true,
    numTotalResults: 95,
  },
  response: {
    resultSets: [
      {
        id: '',
        setType: '',
        exists: true,
        resultsCount: 95,
        results: [
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-07-02',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-22',
            individualId: 'norm-individual-22',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-09-09',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-47',
            individualId: 'norm-individual-47',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-11-25',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-69',
            individualId: 'norm-individual-69',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-10-04',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-60',
            individualId: 'norm-individual-60',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-10-12',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-55',
            individualId: 'norm-individual-55',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-11-14',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-63',
            individualId: 'norm-individual-63',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-10-16',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-54',
            individualId: 'norm-individual-54',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-10-21',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-51',
            individualId: 'norm-individual-51',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-08-25',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-40',
            individualId: 'norm-individual-40',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-06-15',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-19',
            individualId: 'norm-individual-19',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-12-03',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-73',
            individualId: 'norm-individual-73',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-05-02',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-1',
            individualId: 'norm-individual-1',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-08-01',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-34',
            individualId: 'norm-individual-34',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-03-15',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-23',
            individualId: 'rf-individual-23',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-01-03',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-8',
            individualId: 'rf-individual-8',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-04-05',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-39',
            individualId: 'rf-individual-39',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-04-07',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-31',
            individualId: 'rf-individual-31',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-01-08',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-5',
            individualId: 'rf-individual-5',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-02-08',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-18',
            individualId: 'rf-individual-18',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-03-19',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-29',
            individualId: 'rf-individual-29',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-04-09',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-38',
            individualId: 'rf-individual-38',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-01-06',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-9',
            individualId: 'rf-individual-9',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-06-10',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-12',
            individualId: 'norm-individual-12',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-09-19',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-49',
            individualId: 'norm-individual-49',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-08-19',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-33',
            individualId: 'norm-individual-33',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-09-06',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-48',
            individualId: 'norm-individual-48',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-05-19',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-6',
            individualId: 'norm-individual-6',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-12-02',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-71',
            individualId: 'norm-individual-71',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-11-11',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-62',
            individualId: 'norm-individual-62',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-06-03',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-20',
            individualId: 'norm-individual-20',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-09-25',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-41',
            individualId: 'norm-individual-41',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-08-25',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-35',
            individualId: 'norm-individual-35',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-12-17',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-80',
            individualId: 'norm-individual-80',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-07-24',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-24',
            individualId: 'norm-individual-24',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-05-15',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-8',
            individualId: 'norm-individual-8',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-05-04',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-9',
            individualId: 'norm-individual-9',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-07-03',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-29',
            individualId: 'norm-individual-29',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-07-08',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-30',
            individualId: 'norm-individual-30',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-10-11',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-58',
            individualId: 'norm-individual-58',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-09-21',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-45',
            individualId: 'norm-individual-45',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-02-23',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-20',
            individualId: 'rf-individual-20',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-01-06',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-4',
            individualId: 'rf-individual-4',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-03-08',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-26',
            individualId: 'rf-individual-26',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-01-22',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-2',
            individualId: 'rf-individual-2',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-02-10',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-16',
            individualId: 'rf-individual-16',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-03-23',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-22',
            individualId: 'rf-individual-22',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-04-05',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-37',
            individualId: 'rf-individual-37',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-03-21',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-28',
            individualId: 'rf-individual-28',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-11-16',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-65',
            individualId: 'norm-individual-65',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-12-25',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-78',
            individualId: 'norm-individual-78',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-05-15',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-10',
            individualId: 'norm-individual-10',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-08-19',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-32',
            individualId: 'norm-individual-32',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-06-09',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-15',
            individualId: 'norm-individual-15',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-06-17',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-16',
            individualId: 'norm-individual-16',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-10-16',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-52',
            individualId: 'norm-individual-52',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-08-02',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-39',
            individualId: 'norm-individual-39',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-06-23',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-13',
            individualId: 'norm-individual-13',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-12-04',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-77',
            individualId: 'norm-individual-77',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-08-19',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-38',
            individualId: 'norm-individual-38',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-05-20',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-4',
            individualId: 'norm-individual-4',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-07-01',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-28',
            individualId: 'norm-individual-28',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-05-24',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-5',
            individualId: 'norm-individual-5',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-11-18',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-70',
            individualId: 'norm-individual-70',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-04-08',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-35',
            individualId: 'rf-individual-35',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-03-03',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-24',
            individualId: 'rf-individual-24',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-04-14',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-32',
            individualId: 'rf-individual-32',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-02-14',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-11',
            individualId: 'rf-individual-11',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-02-16',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-15',
            individualId: 'rf-individual-15',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-04-21',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-36',
            individualId: 'rf-individual-36',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-02-15',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-12',
            individualId: 'rf-individual-12',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-02-20',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-14',
            individualId: 'rf-individual-14',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-03-09',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-27',
            individualId: 'rf-individual-27',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-01-06',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-6',
            individualId: 'rf-individual-6',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-03-22',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-30',
            individualId: 'rf-individual-30',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-02-02',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-17',
            individualId: 'rf-individual-17',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-01-03',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-3',
            individualId: 'rf-individual-3',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-03-22',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-25',
            individualId: 'rf-individual-25',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-05-06',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-2',
            individualId: 'norm-individual-2',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-10-22',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-59',
            individualId: 'norm-individual-59',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-07-09',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-27',
            individualId: 'norm-individual-27',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-06-23',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-11',
            individualId: 'norm-individual-11',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-06-16',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-18',
            individualId: 'norm-individual-18',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-11-10',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-66',
            individualId: 'norm-individual-66',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-08-22',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-36',
            individualId: 'norm-individual-36',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-12-11',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-74',
            individualId: 'norm-individual-74',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-09-06',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-norm-individual-42',
            individualId: 'norm-individual-42',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258407001',
              label: 'Abscess tissue',
            },
            sampleOriginType: {
              id: 'SNOMED:444941003',
              label: 'Broth medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-02-23',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-13',
            individualId: 'rf-individual-13',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-01-01',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-10',
            individualId: 'rf-individual-10',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-01-09',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-1',
            individualId: 'rf-individual-1',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-04-18',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-34',
            individualId: 'rf-individual-34',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-04-03',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-40',
            individualId: 'rf-individual-40',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-04-04',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-33',
            individualId: 'rf-individual-33',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-02-10',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-19',
            individualId: 'rf-individual-19',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-01-18',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-7',
            individualId: 'rf-individual-7',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
          {
            biosampleStatus: {
              id: 'SNOMED:365641003',
              label: 'Minor blood groups - finding',
            },
            collectionDate: '2023-03-10',
            collectionMoment: 'P32Y6M1D',
            diagnosticMarkers: '',
            histologicalDiagnosis: '',
            id: 'biosample-rf-individual-21',
            individualId: 'rf-individual-21',
            info: {},
            measurements: '',
            notes: '',
            obtentionProcedure: '',
            pathologicalStage: '',
            pathologicalTnmFinding: '',
            phenotypicFeatures: '',
            sampleOriginDetail: {
              id: 'SNOMED:258497007',
              label: 'Abscess swab',
            },
            sampleOriginType: {
              id: 'SNOMED:422236008',
              label: 'Agar medium',
            },
            sampleProcessing: '',
            sampleStorage: '',
            tumorGrade: '',
            tumorProgression: '',
          },
        ],
        resultsHandover: null,
      },
    ],
  },
  beaconHandovers: [],
};

export const query = {
  query: {
    filters: [],
    requestedGranularity: 'record',
    pagination: {
      skip: 0,
      limit: 100,
    },
  },
  meta: {
    apiVersion: 'v2.0',
  },
};
